// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDS.Models;

#nullable disable

namespace SDS.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240131230724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SDS.Models.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("GasoilPrice")
                        .HasColumnType("float");

                    b.Property<float>("SansPlombPrice")
                        .HasColumnType("float");

                    b.HasKey("PriceId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("SDS.Models.Rapport", b =>
                {
                    b.Property<int>("RapportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Equipe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float?>("GasoilCash")
                        .HasColumnType("float");

                    b.Property<float>("GasoilDepart")
                        .HasColumnType("float");

                    b.Property<float?>("GasoilDiff")
                        .HasColumnType("float");

                    b.Property<float>("GasoilFinal")
                        .HasColumnType("float");

                    b.Property<DateTime>("Journee")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Poste")
                        .HasColumnType("int");

                    b.Property<float?>("SansPlombCash")
                        .HasColumnType("float");

                    b.Property<float>("SansPlombDepart")
                        .HasColumnType("float");

                    b.Property<float?>("SansPlombDiff")
                        .HasColumnType("float");

                    b.Property<float>("SansPlombFinal")
                        .HasColumnType("float");

                    b.Property<float?>("Total")
                        .HasColumnType("float");

                    b.HasKey("RapportId");

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("SDS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
