// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDS.Models;

#nullable disable

namespace SDS.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240203164734_ThirdCreate")]
    partial class ThirdCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SDS.Models.Caisse", b =>
                {
                    b.Property<int>("CaisseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Autre")
                        .HasColumnType("float");

                    b.Property<float>("Cheque")
                        .HasColumnType("float");

                    b.Property<float>("ContreBon")
                        .HasColumnType("float");

                    b.Property<float>("Credit")
                        .HasColumnType("float");

                    b.Property<float>("CreditGerant")
                        .HasColumnType("float");

                    b.Property<float>("Depenses")
                        .HasColumnType("float");

                    b.Property<float>("Espece")
                        .HasColumnType("float");

                    b.Property<float>("Filtres")
                        .HasColumnType("float");

                    b.Property<float?>("Fond")
                        .HasColumnType("float");

                    b.Property<DateTime>("Journee")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Lavage")
                        .HasColumnType("float");

                    b.Property<float>("Lubrifiant")
                        .HasColumnType("float");

                    b.Property<float>("Poste1")
                        .HasColumnType("float");

                    b.Property<float>("Poste2")
                        .HasColumnType("float");

                    b.Property<float>("Poste3")
                        .HasColumnType("float");

                    b.Property<float>("SNDP")
                        .HasColumnType("float");

                    b.Property<float>("SortieContreBon")
                        .HasColumnType("float");

                    b.Property<float>("TPE")
                        .HasColumnType("float");

                    b.HasKey("CaisseId");

                    b.ToTable("Caisses");
                });

            modelBuilder.Entity("SDS.Models.Rapport", b =>
                {
                    b.Property<int>("RapportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Equipe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float?>("G1Cash")
                        .HasColumnType("float");

                    b.Property<float>("G1Depart")
                        .HasColumnType("float");

                    b.Property<float?>("G1Diff")
                        .HasColumnType("float");

                    b.Property<float>("G1Final")
                        .HasColumnType("float");

                    b.Property<float?>("G2_1Cash")
                        .HasColumnType("float");

                    b.Property<float>("G2_1Depart")
                        .HasColumnType("float");

                    b.Property<float?>("G2_1Diff")
                        .HasColumnType("float");

                    b.Property<float>("G2_1Final")
                        .HasColumnType("float");

                    b.Property<float?>("G2_2Cash")
                        .HasColumnType("float");

                    b.Property<float>("G2_2Depart")
                        .HasColumnType("float");

                    b.Property<float?>("G2_2Diff")
                        .HasColumnType("float");

                    b.Property<float>("G2_2Final")
                        .HasColumnType("float");

                    b.Property<float?>("G501Cash")
                        .HasColumnType("float");

                    b.Property<float>("G501Depart")
                        .HasColumnType("float");

                    b.Property<float?>("G501Diff")
                        .HasColumnType("float");

                    b.Property<float>("G501Final")
                        .HasColumnType("float");

                    b.Property<float>("G50Price")
                        .HasColumnType("float");

                    b.Property<float>("GasoilPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("Journee")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Poste")
                        .HasColumnType("int");

                    b.Property<float?>("SSP1Cash")
                        .HasColumnType("float");

                    b.Property<float>("SSP1Depart")
                        .HasColumnType("float");

                    b.Property<float?>("SSP1Diff")
                        .HasColumnType("float");

                    b.Property<float>("SSP1Final")
                        .HasColumnType("float");

                    b.Property<float?>("SSP2Cash")
                        .HasColumnType("float");

                    b.Property<float>("SSP2Depart")
                        .HasColumnType("float");

                    b.Property<float?>("SSP2Diff")
                        .HasColumnType("float");

                    b.Property<float>("SSP2Final")
                        .HasColumnType("float");

                    b.Property<float?>("SSP3Cash")
                        .HasColumnType("float");

                    b.Property<float>("SSP3Depart")
                        .HasColumnType("float");

                    b.Property<float?>("SSP3Diff")
                        .HasColumnType("float");

                    b.Property<float>("SSP3Final")
                        .HasColumnType("float");

                    b.Property<float>("SansPlombPrice")
                        .HasColumnType("float");

                    b.Property<float?>("Total")
                        .HasColumnType("float");

                    b.HasKey("RapportId");

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("SDS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
